### ISSUE TITLE
Dolar hoy

### ISSUE THREAD

**Issue by MauricioHernanCabrera** [ftarantuviez/zara#1]
985

**Comment by MauricioHernanCabrera** [comment]
@ftarantuviez

**Comment by ftarantuviez** [comment]
Bueno, eso realmente depende...

Según [Dolar Hoy](https://dolarhoy.com/), la compra está en **$980** y la venta en **$1.000**.

Tenemos que tener más información para poder continuar con el issue.

Cc: @MauricioHernanCabrera
